export const USER_LOGIN="USER_LOGIN"
export const USER_SIGNUP="USER_SIGNUP"
export const USER_FORGET_PASSWORD="USER_FORGET_PASSWORD"
export const USER_CHANGE_PASSWORD="USER_CHANGE_PASSWORD"
export const USER_VERIFY_EMAIL="USER_VERIFY_EMAIL"
export const USER_RESET_PASSWORD="USER_RESET_PASSWORD"





